// adapters/vue3/ModeIndicator.vue
<template><div ref="hostRef"></div></template>
<script setup>
import { ref, onMounted } from 'vue';
import { createModeIndicator } from '../../core/ui-helpers.js';
const hostRef = ref(null);
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!hostRef.value || !props.engine) return;
  const { el } = createModeIndicator(props.engine); hostRef.value.appendChild(el);
});
</script>

// adapters/svelte/ModeIndicator.svelte
<script>
  import { onMount } from 'svelte';
  import { createModeIndicator } from '../../core/ui-helpers.js';
  export let engine = null; let host;
  onMount(() => { if (!host || !engine) return; const { el } = createModeIndicator(engine); host.appendChild(el); });
</script>
<div bind:this={host}></div>
