// adapters/vue3/ModeToast.vue
<template><div ref="hostRef"></div></template>
<script setup>
import { ref, onMounted } from 'vue';
import { createModeToast } from '../../core/ui-helpers.js';
const hostRef = ref(null);
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!hostRef.value || !props.engine) return;
  const { el } = createModeToast(props.engine); hostRef.value.appendChild(el);
});
</script>

// adapters/react/ModeToast.jsx
import { useEffect, useRef } from 'react';
import { useTheme } from './ThemeProvider.jsx';
import { createModeToast } from '../../core/ui-helpers.js';
export default function ModeToastReact() {
  const { engine } = useTheme(); const hostRef = useRef(null);
  useEffect(() => {
    if (!hostRef.current || !engine) return;
    const { el } = createModeToast(engine); hostRef.current.appendChild(el);
  }, [engine]);
  return <div ref={hostRef} />;
}
