// adapters/react/AudioToggle.jsx
import { useEffect, useRef } from 'react';
import { useTheme } from './ThemeProvider.jsx';
import { createAudioToggle } from '../../core/ui-helpers.js';
import { setAudioEnabled } from '../../core/audio-engine.js';
export default function AudioToggleReact() {
  const { engine } = useTheme(); const hostRef = useRef(null);
  useEffect(() => {
    if (!hostRef.current || !engine) return;
    const { el } = createAudioToggle(engine, { setAudioEnabled }); hostRef.current.appendChild(el);
  }, [engine]);
  return <div ref={hostRef} />;
}

// adapters/vue3/AudioToggle.vue
<template><div ref="hostRef"></div></template>
<script setup>
import { ref, onMounted } from 'vue';
import { createAudioToggle } from '../../core/ui-helpers.js';
import { setAudioEnabled } from '../../core/audio-engine.js';
const hostRef = ref(null);
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!hostRef.value || !props.engine) return;
  const { el } = createAudioToggle(props.engine, { setAudioEnabled }); hostRef.value.appendChild(el);
});
</script>
