// adapters/svelte/AudioToggle.svelte
<script>
  import { onMount } from 'svelte';
  import { createAudioToggle } from '../../core/ui-helpers.js';
  import { setAudioEnabled } from '../../core/audio-engine.js';
  export let engine = null; let host;
  onMount(() => { if (!host || !engine) return; const { el } = createAudioToggle(engine, { setAudioEnabled }); host.appendChild(el); });
</script>
<div bind:this={host}></div>

// adapters/vue3/AudioToggle.vue
<template><div ref="hostRef"></div></template>
<script setup>
import { ref, onMounted } from 'vue';
import { createAudioToggle } from '../../core/ui-helpers.js';
import { setAudioEnabled } from '../../core/audio-engine.js';
const hostRef = ref(null);
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!hostRef.value || !props.engine) return;
  const { el } = createAudioToggle(props.engine, { setAudioEnabled }); hostRef.value.appendChild(el);
});
</script>
