// adapters/svelte/LeavesOverlay.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { LeavesOverlay } from '../../core/leaves-overlay.js';
  export let engine = null; let container, overlay;
  onMount(() => { overlay = new LeavesOverlay(container); if (engine?.mode === 'sunny') overlay.activate(); });
  $: if (overlay) { engine?.mode === 'sunny' ? overlay.activate() : overlay.deactivate(); }
  onDestroy(() => overlay?.deactivate());
</script>
<div bind:this={container}></div>

// adapters/vue3/LeavesOverlay.vue
<template><div ref="containerRef"></div></template>
<script setup>
import { ref, watch, onMounted, onUnmounted } from 'vue';
import { LeavesOverlay } from '../../core/leaves-overlay.js';
const containerRef = ref(null); let overlay = null;
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!containerRef.value) return; overlay = new LeavesOverlay(containerRef.value);
  if (props.engine?.mode === 'sunny') overlay.activate();
});
watch(() => props.engine?.mode, (m) => {
  if (!overlay) return; m === 'sunny' ? overlay.activate() : overlay.deactivate();
});
onUnmounted(() => { overlay?.deactivate(); });
</script>
