// adapters/react/ModeIndicator.jsx
import { useEffect, useRef } from 'react';
import { useTheme, MODE_ORDER } from './ThemeProvider.jsx';
import { createModeIndicator } from '../../core/ui-helpers.js';
export default function ModeIndicatorReact() {
  const { engine } = useTheme(); const hostRef = useRef(null);
  useEffect(() => {
    if (!hostRef.current || !engine) return;
    const { el } = createModeIndicator(engine); hostRef.current.appendChild(el);
  }, [engine]);
  return <div ref={hostRef} />;
}

// adapters/vue3/ModeIndicator.vue
<template><div ref="hostRef"></div></template>
<script setup>
import { ref, onMounted } from 'vue';
import { createModeIndicator } from '../../core/ui-helpers.js';
const hostRef = ref(null);
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!hostRef.value || !props.engine) return;
  const { el } = createModeIndicator(props.engine); hostRef.value.appendChild(el);
});
</script>
