// adapters/react/MoonOverlay.jsx
import { useRef, useEffect } from 'react';
import { useTheme } from './ThemeProvider.jsx';
import { MoonOverlay } from '../../core/canvas-moon.js';
export default function MoonOverlayReact() {
  const { mode, engine } = useTheme();
  const containerRef = useRef(null); const overlayRef = useRef(null);
  useEffect(() => {
    if (!containerRef.current) return;
    if (!overlayRef.current) overlayRef.current = new MoonOverlay(containerRef.current);
    const ov = overlayRef.current;
    if (mode === 'midnight') ov.activate(); else ov.deactivate();
  }, [mode]);
  return <div ref={containerRef} />;
}

// adapters/vue3/MoonOverlay.vue
<template><div ref="containerRef"></div></template>
<script setup>
import { ref, watch, onMounted, onUnmounted } from 'vue';
import { MoonOverlay } from '../../core/canvas-moon.js';
const containerRef = ref(null); let overlay = null;
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!containerRef.value) return;
  overlay = new MoonOverlay(containerRef.value);
  if (props.engine?.mode === 'midnight') overlay.activate();
});
watch(() => props.engine?.mode, (m) => {
  if (!overlay) return; m === 'midnight' ? overlay.activate() : overlay.deactivate();
});
onUnmounted(() => { overlay?.deactivate(); });
</script>
