// adapters/react/SnowOverlay.jsx
import { useRef, useEffect } from 'react';
import { useTheme } from './ThemeProvider.jsx';
import { SnowOverlay } from '../../core/canvas-snow.js';
export default function SnowOverlayReact() {
  const { mode } = useTheme();
  const containerRef = useRef(null); const overlayRef = useRef(null);
  useEffect(() => {
    if (!containerRef.current) return;
    if (!overlayRef.current) overlayRef.current = new SnowOverlay(containerRef.current);
    if (mode === 'snow') overlayRef.current.activate(); else overlayRef.current.deactivate();
  }, [mode]);
  return <div ref={containerRef} />;
}

// adapters/vue3/SnowOverlay.vue
<template><div ref="containerRef"></div></template>
<script setup>
import { ref, watch, onMounted, onUnmounted } from 'vue';
import { SnowOverlay } from '../../core/canvas-snow.js';
const containerRef = ref(null); let overlay = null;
const props = defineProps({ engine: Object });
onMounted(() => {
  if (!containerRef.value) return; overlay = new SnowOverlay(containerRef.value);
  if (props.engine?.mode === 'snow') overlay.activate();
});
watch(() => props.engine?.mode, (m) => {
  if (!overlay) return; m === 'snow' ? overlay.activate() : overlay.deactivate();
});
onUnmounted(() => { overlay?.deactivate(); });
</script>
